# Generated by Django 3.1.4 on 2021-03-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_date_closed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='created',
            new_name='created_datetime',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='created',
            new_name='created_datetime',
        ),
    ]
