# Generated by Django 3.1.4 on 2021-03-22 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210322_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='date_closed',
            new_name='date_closed_datetime',
        ),
    ]
