# Generated by Django 3.1.4 on 2021-03-25 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210322_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_datetime',
        ),
    ]
