# Generated by Django 3.1.4 on 2021-03-26 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_remove_user_created_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='contact',
            field=models.IntegerField(default=774672776, validators=[django.core.validators.MaxLengthValidator(9), django.core.validators.MinLengthValidator(9)]),
            preserve_default=False,
        ),
    ]
