# Generated by Django 3.1.4 on 2021-03-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_listing_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date_closed_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
