# Generated by Django 3.1.4 on 2021-03-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20210326_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilepicture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
