# Generated by Django 4.0.2 on 2022-02-20 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_user_profilepicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profilepicture',
        ),
    ]
