# Generated by Django 4.0.2 on 2022-02-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_listing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Closed')], default='1', max_length=1),
        ),
    ]
