# Generated by Django 4.0.2 on 2022-02-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_listing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date_closed_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
